//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRF : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean UI
        {
            get
            {
                return SteamVR_Actions.vRF_UI;
            }
        }
        
        public virtual SteamVR_Action_Boolean PullTrigger
        {
            get
            {
                return SteamVR_Actions.vRF_PullTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.vRF_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Up
        {
            get
            {
                return SteamVR_Actions.vRF_D_Up;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Left
        {
            get
            {
                return SteamVR_Actions.vRF_D_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Down
        {
            get
            {
                return SteamVR_Actions.vRF_D_Down;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Right
        {
            get
            {
                return SteamVR_Actions.vRF_D_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.vRF_Grab;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.vRF_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.vRF_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.vRF_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vRF_Haptic;
            }
        }
    }
}
